### ISSUE TITLE
SectionList and Flatlist not scrolling inside reanimated-bottom-sheet

### ISSUE THREAD

**Issue by rizshivalli** [osdnk/react-native-reanimated-bottom-sheet#123] opened 2019-11-13 09:41 UTC
I have added a SectionList (also tried with FlatList) and the scroll for SectionList or Flatlist is not working inside react-native-reanimated-bottom-sheet
`       <BottomSheet
        enabledInnerScrolling={true}
        ref={fullScreen}
        snapPoints={[450, '80%', '50%', '50%']}

        initialSnap={2}

         overdragResistanceFactor={1}

        renderContent={() => renderBottomContent() }

        enabledContentGestureInteraction={false}

      /> `

the SectionList is displaying but it is not scrolling as normal behaviour.

**Comment by jasonkw9** [comment] 2019-11-20 04:33
Duplicate of #20

**Comment by Arvi128** [comment] 2020-01-27 11:39
Here's my solution : 

`  <BottomSheet
        snapPoints={[0, hp('60%'), ACTUAL_SCREEN_HEIGHT]}
        initialSnap={1}
        onOpenEnd={() => {
          this.setState({allowScrolling: true});
        }}
        enabledInnerScrolling={true}
        onCloseStart={() => this.setState({allowScrolling: false})}
        onCloseEnd={() =>
          this.props.onBackdropPress()
        }
        enabledGestureInteraction={true}
        overdragResistanceFactor={0}
        enabledHeaderGestureInteraction={true}
        enabledContentGestureInteraction={!this.state.allowScrolling}
        renderContent={this.renderContent}
        renderHeader={this.renderHeader}
      />`


If you want the inner content to be scrollable , make sure enabledContentGestureInteraction is set to false. 
I wanted the scroll to work only when the view is at a certain height ( i.e full screen or half screen), find out the position of the scroll. For example : 

`   <VirtualizedList
          showVerticalScrollIndicator={false}
          ref={ref => (this.scrollView = ref)}
          onScroll={event => {
            //Find out the scroll position based on your device height and stop scrolling accordingly
            if (event.nativeEvent.contentOffset.y < 10) {
              this.setState({allowScrolling: false});
            }
          }}
          data={this.props.options}
          getItemCount={data => this.props.options.length}
          getItem={(data, index) => {
            return data[index];
          }}
          keyExtractor={(item, index) => {
            return item.id;
          }}
          onEndReached={() => console.log('End Reached')}
          renderItem={this.renderItem}
        />`

**Closed** 2020-01-28 04:09 UTC
