### ISSUE TITLE
Android: Swipe not working.

### ISSUE THREAD

**Issue by luvnish19** [osdnk/react-native-reanimated-bottom-sheet#127] opened 2019-11-18 12:39 UTC
I append this example in my code and what I noticed that swipe gesture (slide) is not working.
I only run this in Android device. HERE is my source code:

import React from 'react'
import {
  Image,
  StyleSheet,
  Text,
  TouchableWithoutFeedback,
  View,
  TouchableOpacity
} from 'react-native'
import BottomSheet from 'reanimated-bottom-sheet'

export default class AnimatedBottomSheet extends React.Component {
  renderInner = () => (
    <View style={styles.panel}>
      <Text style={styles.panelTitle}>San Francisco Airport</Text>
      <Text style={styles.panelSubtitle}>
        International Airport - 40 miles away
      </Text>
      <View style={styles.panelButton}>
        <Text style={styles.panelButtonTitle}>Directions</Text>
      </View>
      <View style={styles.panelButton}>
        <Text style={styles.panelButtonTitle}>Search Nearby</Text>
      </View>
      <Image  style={{height:80,width:80,backgroundColor:'green'}} 
        style={styles.photo}
       />
    </View>
  )

  renderHeader = () => (
    <View style={styles.header}>
      <View style={styles.panelHeader}>
        <View style={styles.panelHandle} />
      </View>
    </View> )

  bs = React.createRef()

  render() {
    return (
      <View style={styles.container}>
        <BottomSheet
          ref={this.bs}
        
          snapPoints={[450, '80%', '50%', '50%']}
          renderContent={this.renderInner}
          renderHeader={this.renderHeader}
          initialSnap={3}
          overdragResistanceFactor={1}
          enabledInnerScrolling={true}
          enabledGestureInteraction={true}
          enabledHeaderGestureInteraction={true}
          enabledContentGestureInteraction={false} />

        <TouchableWithoutFeedback style={{height:80,width:80,backgroundColor:'red'}} onPress={() => this.bs.current.snapTo(1)}>
          <Image style={styles.map}  />
        </TouchableWithoutFeedback>
      </View>
    )
  }
}

const IMAGE_SIZE = 200

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF',
  },
  box: {
    width: IMAGE_SIZE,
    height: IMAGE_SIZE,
  },
  panelContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  panel: {
    height: 600,
    padding: 20,
    backgroundColor: '#f7f5eee8',
  },
  header: {
    backgroundColor: '#f7f5eee8',
    shadowColor: '#000000',
    paddingTop: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  panelHeader: {
    alignItems: 'center',
  },
  panelHandle: {
    width: 40,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00000040',
    marginBottom: 10,
  },
  panelTitle: {
    fontSize: 27,
    height: 35,
  },
  panelSubtitle: {
    fontSize: 14,
    color: 'gray',
    height: 30,
    marginBottom: 10,
  },
  panelButton: {
    padding: 20,
    borderRadius: 10,
    backgroundColor: '#318bfb',
    alignItems: 'center',
    marginVertical: 10,
  },
  panelButtonTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: 'white',
  },
  photo: {
    width: '100%',
    height: 225,
    marginTop: 30,
  },
  map: {
    height: '100%',
    width: '100%',
  },
})

Please fix this one. Thanks

**Comment by akinmac002** [comment] 2019-11-18 14:32
I have the same problem.

**Comment by akinmac002** [comment] 2019-11-18 14:32
I have that same problem.

**Comment by feedcast-me** [comment] 2019-11-19 01:38
same here, any workaround?

**Comment by rtanizawa** [comment] 2019-11-19 02:11
I'm having the same issue here

**Comment by luvnish19** [comment] 2019-11-19 03:40
@osdnk please provide a solution for this. Everyone is in trouble.

**Comment by akinmac002** [comment] 2019-11-19 06:49
Working properly in another project. I think that the problem is gesture-handler or reanimated conflict.

**Comment by luvnish19** [comment] 2019-11-19 06:50
@akinmac002 Please share your source code. So that we could run as it is.

**Comment by akinmac002** [comment] 2019-11-19 08:48
I solved my problem. I've detected the problem as linking on react-native-gesture-handler. https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#android

Edit this:

```
package com.swmansion.gesturehandler.react.example;

import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }

+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+       return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
+  }
}
```

**Comment by luvnish19** [comment] 2019-11-20 07:03
It works. Thanks a lot

**Comment by raajnadar** [comment] 2019-11-20 12:20
Yes, this docs helped me https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#android

Please close the issue

**Closed** 2019-11-21 03:46 UTC

**Comment by azhararmar** [comment] 2020-03-08 16:13
For me even it did not work even after doing all configuration as specified in installation document.

I added following code in `index.js` of the app and it worked perfectly for me.

```
import 'react-native-gesture-handler';
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import { gestureHandlerRootHOC } from 'react-native-gesture-handler'

AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
```

**Comment by alexeyvax** [comment] 2020-11-26 18:08
I did all steps you guys @akinmac002 @azhararmar provided but swipe still does not work for me (

**Comment by qtrgq** [comment] 2021-01-11 14:04
@alexeyvax It doesn't work for me too. Did you solve this issue ?

**Comment by Kailash23** [comment] 2021-02-21 11:25
> For me even it did not work even after doing all configuration as specified in installation document.
> 
> I added following code in `index.js` of the app and it worked perfectly for me.
> 
> ```
> import 'react-native-gesture-handler';
> import {AppRegistry} from 'react-native';
> import App from './App';
> import {name as appName} from './app.json';
> import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> 
> AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> ```

This worked
Thanks

**Comment by pabloluz** [comment] 2021-05-09 03:24
Since I already had `import 'react-native-gesture-handler'` on top of my `index.js`, by simply adding the following fixed the issue, without any changes on `MainActivity.java`:

> ```
> AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> ```

Thanks, azhararmar.

**Comment by nielpattin** [comment] 2021-11-29 08:16
> For me even it did not work even after doing all configuration as specified in installation document.
> 
> I added following code in `index.js` of the app and it worked perfectly for me.
> 
> ```
> import 'react-native-gesture-handler';
> import {AppRegistry} from 'react-native';
> import App from './App';
> import {name as appName} from './app.json';
> import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> 
> AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> ```

Thank you soooo much

**Comment by alihaydar56** [comment] 2022-11-06 12:14
> For me even it did not work even after doing all configuration as specified in installation document.
> 
> I added following code in `index.js` of the app and it worked perfectly for me.
> 
> ```
> import 'react-native-gesture-handler';
> import {AppRegistry} from 'react-native';
> import App from './App';
> import {name as appName} from './app.json';
> import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> 
> AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> ```

works for me,thanks azhararmar.

**Comment by phamhieu1412** [comment] 2022-12-22 07:45
use 
import { GestureHandlerRootView } from 'react-native-gesture-handler';


<GestureHandlerRootView style={styles.containerDefault}>
   <BottomSheet ... />
</GestureHandlerRootView>

is working with me
